<Project ToolsVersion="15.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFrameworkVersion>v4.5.2</TargetFrameworkVersion>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="System.Windows.Forms" />
    <Reference Include="System.Web" />
  </ItemGroup>
  <ItemGroup>
    <None Include="packages.config" />
    <ProjectReference Include="..\Dati\Dati.csproj" />
  </ItemGroup>
</Project>
