name: Pulisci Storico Workflow
on:
  workflow_dispatch: # Ti permette di avviarlo manualmente dalla tab "Actions"

jobs:
  del_runs:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: read
    steps:
      - name: Elimina tutte le esecuzioni passate
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 0  # 0 elimina tutto l'archivio
          keep_minimum_runs: 0
